// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuInfo() {
  return window['go']['main']['App']['GetCpuInfo']();
}

export function GetDiskInfo() {
  return window['go']['main']['App']['GetDiskInfo']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetRamInfo() {
  return window['go']['main']['App']['GetRamInfo']();
}

export function ReadyTray() {
  return window['go']['main']['App']['ReadyTray']();
}
