// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {metrics} from '../models';

export function GetCpuInfo():Promise<metrics.CpuInfo>;

export function GetDiskInfo():Promise<Array<metrics.DiskInfo>>;

export function GetNetworkInfo():Promise<Array<metrics.NetworkInfo>>;

export function GetRamInfo():Promise<metrics.RamInfo>;
